/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM
    id("org.jetbrains.kotlin.jvm").version("1.3.10")

    // Apply the application to add support for building a CLI application
    application
}

repositories {
    mavenLocal()
    jcenter()
    maven(url = "https://jitpack.io")
}

dependencies {
    // Use the Kotlin JDK 8 standard library
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("com.github.cdietze:parsek:42f51d0")
//    implementation("com.github.cdietze:parsek-jvm:1.0-SNAPSHOT")

    // Use the Kotlin test library
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    val day = project.findProperty("day") ?: "01"
    println("Running day $day")
    // Define the main class for the application
    mainClassName = "advent2018.day$day.Day${day}Kt"
}
